language: node_js
node_js:
- 8.6.0
addons:
  ssh_known_hosts:
  - 129.211.43.59
install:
- npm install
script:
- npm run build
after_success:
- rsync -az --delete ./dist/* <USERNAME>@<HOST>:<TARGET-PATH>